### ISSUE TITLE
Synology deployment

### ISSUE THREAD

**Issue by vstrong-info** [Kellphy/Nodepay#2] opened 2024-06-07 11:35 UTC
I Deployed it in multiple Docker environments without any issues.

It fails when i deploy it on **Synology** DS412+ 
CPU: 2 core INTEL Atom D2700
DSM: 6.2.4-25556 Update 7

Here is the log:
2024-06-07 11:28:47,304 - INFO - Starting the script 1.0.1...
Traceback (most recent call last):
  File "//main.py", line 139, in <module>

)
  File "//main.py", line 73, in run
    driver = webdriver.Chrome(options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x7f65209fd07e <unknown>
#1 0x7f65206d58d7 <unknown>
#2 0x7f652070b0cd <unknown>
#3 0x7f65207074c1 <unknown>
#4 0x7f6520703f42 <unknown>
#5 0x7f652074c8c9 <unknown>
#6 0x7f652073eb23 <unknown>
#7 0x7f652070f52d <unknown>
#8 0x7f65207102e2 <unknown>
#9 0x7f65209cc956 <unknown>
#10 0x7f65209cfd1a <unknown>
#11 0x7f65209cf7cf <unknown>
#12 0x7f65209d01a5 <unknown>
#13 0x7f65209bdb6f <unknown>
#14 0x7f65209d04e0 <unknown>
#15 0x7f65209a6d16 <unknown>
#16 0x7f65209ed805 <unknown>
#17 0x7f65209ed9f2 <unknown>
#18 0x7f65209fc56a <unknown>
#19 0x7f651f993134 <unknown>

**Comment by Kellphy** [comment] 2024-06-09 20:01
Hmm, out of curiosity, can you run `uname -a`?

**Comment by vstrong-info** [comment] 2024-06-10 14:58
> Hmm, out of curiosity, can you run `uname -a`?
```
uname -a
Linux MYSERVER 3.10.105 #25556 SMP Tue Mar 21 22:22:21 CST 2023 x86_64 GNU/Linux synology_cedarview_412+
```

**Comment by xx12306** [comment] 2024-06-14 05:05
> Hmm, out of curiosity, can you run `uname -a`?

Same as me, Wonder how much hard disk space is needed to run it, I only have 1.3G spare

```
uname -a
Linux vultr 4.14.12-041412-generic #201801051649 SMP Fri Jan 5 16:50:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Kellphy** [comment] 2024-06-22 15:22
![image](https://github.com/Kellphy/Nodepay/assets/46824693/f49bca8f-0d4f-4ada-9313-05eaa7863e60)
about 200mb of RAM, I wonder if the x86 architecture has an issue with the chromedriver python package

**Comment by Kellphy** [comment] 2024-06-22 15:25
I deployed on an x86
```
# uname -a
Linux e40d5d9d2503 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux
```
and it works, but yours both fail at:
driver = webdriver.Chrome(options=chrome_options)
hmm ...

**Comment by Kellphy** [comment] 2024-06-22 16:00
For testing purposes, can you try running with this legacy tag:
```
docker run -d \
  --name Nodepay \
  --restart unless-stopped \
  -e NP_COOKIE="YOURCOOKIE" \
  kellphy/nodepay:legacy
  ```
  i made a legacy tag for the legacy chromedriver headless mode
  the script should start with:
  ```
  Starting the script 1.0.2.L...
  ```

**Comment by Kellphy** [comment] 2024-06-28 09:41
I will mark this one as duplicate of https://github.com/Kellphy/Nodepay/issues/4, we can continue the discussion there :)

**Closed as completed by Kellphy** 2024-06-28 09:41 UTC
